### ISSUE TITLE
Getting error using with Firebase Functions

### ISSUE THREAD

**Issue by orhanavan** [freshfox/node-fs-firebase#1]
...\functions\node_modules\node-fs-firebase\dist\app\index.js'. Please verify that the package.js
on has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\...\js-learning\alpha\functions\index.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
!  We were unable to load your functions code. (see above)

**Comment by dominicbartl** [comment]
Hello, thank you for reporting this. Seems like there's an invalid value in the main field.

You can import it from `node-fs-firebase/dist/lib` for now. I'll publish a fix today.
